
# Site settings
baseurl = "/"
disqusShortname = "adrianstipanov-com"
googleAnalytics = "UA-21961158-2"
languageCode = "en-us"
title = "Adrian Stipanov"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
author = "Adrian Stipanov"
description = "A blog about investing, entrepreneurship and life"
tagline = "Notes from the underground"

twitter = "AdrianStipanov"
facebook = ""


