
# Site settings
baseurl = "/"
googleAnalytics = "UA-21961158-2"
languageCode = "en-us"
title = "Adrian Stipanov"
theme = "solar-theme-hugo"
scheme = "light"
pygmentsStyle = "solarized-light" #solarized-light, -dark or -dark256
copyright = "©Adrian Stipanov - 2020"

[taxonomies]
    tag = "tags"
[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
enableGoogleAnalytics = true
enableDisqus = true
disqusShortname = "adrianstipanov-com"
scheme = "light" # light, dark, gray or preference
author = "Adrian Stipanov"
description = "Notes from the underground..."

twitter_username = "AdrianStipanov"
paginate = 5


